### ISSUE TITLE
readings above 25C with TSIC306

### ISSUE THREAD

**Issue by travisdobias** [grillbaer/python-tsic#1]
Hi, playing around with your demo code and a TSIC 306 from B+B Sensors on a raspberry PI GPIO 14, 3.3V.  

The TSIC.measurement method does not seem to return values above 25c, as soon as the chip cools below 25c, the readings are updated.

**Comment by grillbaer** [comment]
I'm using this code with six TSIC 306 sensors in a data logger for my heating system all the time. There are often temperatures up to nearly 50°C. Perhaps a problem with the signal or timing.

What's the output of 'tsic.py --type 306 14' when above 25°C?
Are the readings correct when below 25°C?

Do you have a 100nF capacitor connected to the sensor's voltage supply pins very close to the sensor?
Is it the only sensor connected or are there more of them?

**Comment by travisdobias** [comment]
Hi, above 25c, it returns the last valid reading (e.g. 24.947 or something like that) until the temp drops below 25.  Below 25c readings seem correct.

No other sensors connected to the board

I have not put a capacitor between the voltage pins; but i can try that; 

hoping to use it to go upto 120c or so for a PID application on a coffee machine to replace the DS18B20 sensor which cannot read about 100c

thanks!

**Comment by grillbaer** [comment]
Ok, please try the 100nF capacitor to exclude voltage supply problems. The data sheet https://shop.bb-sensors.com/out/media/Datasheet_Digital_Semiconductor_temperatur_sensor_TSIC.pdf says in "Operating data":
External capacitance between V+ and Gnd: min. 80 typ. 100 max. 470 nF 
The connection of the blocking capacitor must be done as near as possible to the connection pins of the component.

**Comment by grillbaer** [comment]
Did the capacitor help?

**Comment by travisdobias** [comment]
I didn’t have the right capacitor at hand, so new one should be arriving in the post.  I’ll retest as soon as I can and let you know.

Looking forward to getting it working - many thanks for publishing your code!

kind regards

**Comment by stephan11111** [comment]
Hi , recently bought a tsic 306 and had the same issue. Setting was also same (raspberry 3, 3.3V) Readings above a certain temperature didn't work. However using a small C++ program (downloaded somewhere else), the sensor readings were always correct.
So I did enabled the print output already included in the code and got the following.
[Log tsic.xlsx](https://github.com/grillbaer/python-tsic/files/2973559/Log.tsic.xlsx)

it shows that the signal for the 2nd byte is not detected. 

Solution was, to reduce the waiting time for the second byte to something around 110 ticks (in line 149 of your code). Not sure if 110 is the correct value but it works fine for me ;)

Thanks for making the code available, helped me a lot!


regards

**Comment by grillbaer** [comment]
Thank you @stephan11111 for this great hint!

I took a look into the application notes again. It says that there is a one bit-frame-length high phase to separate bytes (nominal 125µs). Together with the high phase from the preceding bit, this separation should be between 1.25\*125µs=156µs and 1.75\*125µs=219µs, depending on the last bit of the first byte. The maximum length high phase from a regular bit is 0.75\*125µs=95µs. So my limit of 150µs was clearly not a robust choice. A good threshold length should therefore be one bit-frame-length of nominal 125µs.

**I just changed the threshold to 2*duration of the initial t-strobe-low which is nominal 125µs and should also adapt to the individual sensor's timing.**

---
Since I now own an oscilloscope, I just measured the signals from a TSIC 306 from IST AG (don't have one from B+B) for verification. Maybe the B+B sensor has a slightly different timing.

Below 25°C with 230µs byte separation high-phase (full signal on top, zoomed separation on bottom):
![ist-tsic-306-below-25](https://user-images.githubusercontent.com/33845511/54472968-b3b17800-47d1-11e9-86f3-92a2a9de3b93.png)

Above 25°C with 167µs byte separation high-phase:
![ist-tsic-306-above-25](https://user-images.githubusercontent.com/33845511/54472971-bc09b300-47d1-11e9-88f3-d04c2d22ee54.png)

You can clearly see that the byte separation is shorter when the last bit of the first byte becomes set above 25°C, thus leading to the bug.

Regards,
Holger

**Comment by travisdobias** [comment]
FYI - the 100nF capacitor did not resolve the issue, but changing the frame length to 110 and/or 125µs both work fine, and the readings above 25c now returned correctly.  Thanks!

/edit - I took your code change, this of course also works. I will try to close the issue.

**Comment by grillbaer** [comment]
Great, happy that it's working now:-)
