### ISSUE TITLE
Unable to use with PI PICO

### ISSUE THREAD

**Issue by SChandrapuri** [grillbaer/python-tsic#4]
I was using this library, but it is not taking PIGPIO library in PI PICO.
Please help me in this regard. Please guide me that how to use this library for PI PICO

**Comment by grillbaer** [comment]
Hi Sateesh,

Pigpio only supports Linux-based systems as far as I know, see http://abyz.me.uk/rpi/pigpio/index.html for details. It consists of a daemon process installed in the Linux system and a Python library to use it from Python. Pi Pico is only a microcontroller which is not capable of running Linux, so Pigpio will not work there. My TSIC library needs Pigpio and will therefore also not work on Pi Pico. Sorry.

If you are free to choose Arduino (C/C++) as a development platform instead of Micropython, you might use https://github.com/tripplefox/TsicSensor from a friend of mine.

Regards,
Holger

**Comment by SChandrapuri** [comment]
Thanks a lot, Holger
I will try with C/C++.

Regards,
Sateesh Chandrapuri, M.E.
Senior Scientist,
Instrumentation Division,
105# Ground Water Building,
CSIR-National Geophysical Research Institute,
Hyderabad,   500 007
INDIA
Phone :   (O) +91  40-27012630
               (R) +91  40-27200767
               (M) +91 94-91869489
Mail :   ***@***.***
           ***@***.***
           ***@***.***
